### PR TITLE
C [#COR-1106] Make it possible to change the algorithm used to encryp…

### PR DESCRIPTION
**Pull request by austinmoore**
…t the JWT to an asymmetric (a.k.a. public/private key) encryption (e.g. RSA)

http://shore.myjetbrains.com/youtrack/issue/COR-1106

### CODE REVIEW

**Comment by kdelchev** [comment]
I don't see tests with RSA algorithm according to the docs https://github.com/jwt/ruby-jwt#algorithms-and-usage. Should we have one? As I understand current implementation is still with HMAC, correct?

Is it good idea to whitelist the algorithms? Not all algorithms are supported by `ruby-jwt`.

**Comment by kdelchev** [comment]
You can also remove `JWT_ALGORITHM` constant https://github.com/shore-gmbh/shore-ruby-client/blob/chore/COR-1106-jwt-encryption/lib/shore/client/tokens/access_token.rb#L22 since it is not used anymore.

**Comment by austinmoore** [comment]
> I don't see tests with RSA algorithm according to the docs https://github.com/jwt/ruby-jwt#algorithms-and-usage. Should we have one?
> I don't think we need one. That would be testing ruby-jwt. I'll just assume it works.
> 
> As I understand current implementation is still with HMAC, correct?
> Correct. I'm going to do the deployment in two steps. See https://shore.myjetbrains.com/youtrack/issue/COR-1106#comment=100-6404.
> 
> Is it good idea to whitelist the algorithms? Not all algorithms are supported by ruby-jwt.
> I don't think I need to whitelist, but I'll add a test to make sure that unsupported algorithms raise the expected error.

**Comment by kdelchev** [comment]
Ok, looks great. 👍

**Pull request merged**
